spring:
  application:
    name: trac-nghiem-online
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/petlovemain20110447
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
jwt:
  secret: gfdfodwookaq1mdmcmssskqlspmfmkdliwldmalqsfgfdgfgbgfb
default:
  password: 123456
#  port: 3456

